/--
A representation of a programming language.

Progams in language `L` that take inputs of type `I` and return outputs of type `O` have type `L.Prog I O`.
Each language has an associated evaluator, so that program `p` can be run on input `x` with `L.eval p x`.
-/
structure Lang where
  /-- The type of programs. -/
  Prog: Type → Type → Type
  /-- Evaluates a program on an input. -/
  eval: {I O : Type} → Prog I O → I → O

/-- An interpreter for `S` written in `T`: a `T`-program that takes a source program and its input, and produces the output. -/
structure Interp {I O : Type} (S T : Lang) where
  /-- The interpreter program. -/
  prog: T.Prog (S.Prog I O × I) O
  /-- Running the interpreter yields the same result as evaluating the source program directly. -/
  correct: ∀ (p : S.Prog I O) (x: I), S.eval p x = T.eval prog (p, x)

/-- The raw program type of an interpreter for `S` in `T`. -/
abbrev Interp.ProgType (I O : Type) (S T : Lang) :=
  T.Prog (S.Prog I O × I) O

/-- A compiler from `S` to `T` written in `T`: a `T`-program that takes a source program from `I` to `O` and returns a `T` program from `I` to `O`. -/
structure Compiler {I O : Type} (S T : Lang) where
  /-- The compiler program.-/
  prog: T.Prog (S.Prog I O) (T.Prog I O)
  /-- Compiling and running a program yileds the same result as evaluating the source program directly. -/
  correct: ∀ (p : S.Prog I O) (x : I), S.eval p x = T.eval (T.eval prog p) x

/-- The raw program type of a compiler from `S` to `T`. -/
abbrev Compiler.ProgType (I O : Type) (S T : Lang) :=
  T.Prog (S.Prog I O) (T.Prog I O)

/-- A specializer (partial evaluator) for `T`: a `T`-program that takes a program expecting a static-dynamic pair and a static input, and produces a residual program over just the dynamic input. -/
structure Mix (T : Lang) where
  /-- The partial evaluator program, polymorphic over instantiation. -/
  prog: {St Dy O : Type} → T.Prog ((T.Prog (St × Dy) O) × St) (T.Prog Dy O)
  /-- The residual program is equivalent to the original with the static input fixed at all instantiations. -/
  correct: ∀ {St Dy O : Type} (p : T.Prog (St × Dy) O) (s : St) (x : Dy),
    T.eval p (s, x) = T.eval (T.eval prog (p, s)) x

/-- First Futamura projection: specializing an interpreter to a program yields a compiled program. -/
def projection1 {I O : Type}
    (S T : Lang) (mix : Mix T) (interp : @Interp I O S T) (p : S.Prog I O) : T.Prog I O :=
  T.eval mix.prog (interp.prog, p)

/-- The compiled program behaves the same as the source program. -/
theorem projection1_correct {I O : Type}
    (S T : Lang) (mix : Mix T)
    (interp : @Interp I O S T) (p : S.Prog I O)
    (x : I) :
    S.eval p x = T.eval (projection1 S T mix interp p) x := by
  unfold projection1
  rw [← Mix.correct]
  rw [← Interp.correct]

/-- Second Futamura projection: specializing `mix` to an interpreter yields a compiler. -/
def projection2 {I O : Type}
    (S T : Lang)
    (mix : Mix T)
    (interp : @Interp I O S T) : @Compiler I O S T where
  prog := T.eval mix.prog (mix.prog, interp.prog)
  correct := by
    intro p x
    rw [← mix.correct]
    rw [← mix.correct]
    rw [← Interp.correct]

/-- Third Futamura projection: specializing `mix` on `mix` to yields a compiler generator from any language to the implementaion language of `mix`. -/
def projection3 {I O : Type}
    (S T : Lang)
    (mix : Mix T)
    : T.Prog (Interp.ProgType I O S T) (Compiler.ProgType I O S T) :=
  T.eval mix.prog (mix.prog, mix.prog)

/-- Given an interpreter, the generated compiler behaves identically to the interpreter for all input programs and program inputs. -/
theorem projection3_correct {I O : Type}
    (S T : Lang)
    (mix : Mix T)
    (interp : Interp.ProgType I O S T)
    (p : S.Prog I O) (x : I) :
    T.eval interp (p, x) = T.eval (T.eval (T.eval (projection3 S T mix) interp) p) x := by
  unfold projection3
  rw [← mix.correct]
  rw [← mix.correct]
  rw [← mix.correct]

/-- Compiling a program with `projection1` and via the compiler generated by `projection2` yields the same compiled program. -/
theorem projection2_agrees_with_1 {I O : Type}
    (S T : Lang) (mix : Mix T) (interp : @Interp I O S T) (p : S.Prog I O) :
    projection1 S T mix interp p = T.eval (projection2 S T mix interp).prog p := by
  unfold projection1 projection2
  simp
  rw [← mix.correct]

/-- Given an interpreter, `projection2` and `projection3` yield the same compiler. -/
theorem projection3_agrees_with_2 {I O : Type}
    (S T : Lang)
    (mix : Mix T)
    (interp : @Interp I O S T) :
    (projection2 S T mix interp).prog = T.eval (projection3 S T mix) interp.prog := by
  unfold projection2 projection3
  simp
  rw [← mix.correct]
